services:
  db:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d:ro
    networks:
      - todo-network

  web:
    build: .
    container_name: todo-flask
    restart: always
    ports:
      - "${FLASK_PORT}:5000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - todo-network

networks:
  todo-network:

volumes:
  mysql_data: